apiVersion: v1
kind: Service
metadata:
  name: cluster-service
spec:
  selector:
    app: webapp
    app: vehiclemanagementapi
    app: auditlogservice
    app: azuresql
    app: customermanagementapi
    app: workshopmanagementapi
    app: logserver
    app: mailserver
    app: rabbitmq
    app: workshopmanagementeventhandler
  ports:
    - name: http
      port: 80  
      targetPort: 7005
  type: ClusterIP  
