apiVersion: v1
kind: Service
metadata:
  name: cluster-service
spec:
  selector:
    app: webapp
    app: vehiclemanagementapi
  ports:
    - name: http
      port: 80  
      targetPort: 7005
  type: ClusterIP  
