---
apiVersion: v1
kind: ConfigMap
metadata:
  name: defaultuser
data:
  username: rabbitmquser
---
apiVersion: v1
kind: Secret
metadata:
  name: defaultpass
data:
  password: REVCbWJ3a1Nyenk5RDFUOWNKZmE=

