---
apiVersion: v1
kind: ConfigMap
metadata:
  name: defaultuser
data:
  default_user: rabbitmquser
---
apiVersion: v1
kind: Secret
metadata:
  name: defaultpass
data:
  default_pass: REVCbWJ3a1Nyenk5RDFUOWNKZmE=

