---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 0.5Gi