---
apiVersion: v1
kind: Service
metadata:
  name: pitstopservice
  labels:
    env: dev
spec:
  type: NodePort
  selector:
    app: pitstop
  ports:
    - nodePort: 31000
      targetPort: 15672
      port: 15672
      protocol: TCP