---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name:  rabbitmq-deploy
  labels:
    env: dev
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata: 
      name: rabbitmq-pod
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq-con
          image: rabbitmq:3-management-alpine
          env:
            - name: RABBITMQ_CONFIG_FILE
              value: '/etc/pitstop/rabbitmq.conf' 
          volumeMounts: 
            - name: rabbitmq
              mountPath: /etc/pitstop/rabbitmq/ 
            - name: rabbitmq-pvc 
              mountPath: /var/lib/rabbitmq
          ports: 
            - containerPort: 15672
            - containerPort: 5672
              protocol: TCP
      volumes: 
        - name: rabbitmq
          configMap: 
            name: rabbbitmq.conf
          persistentVolumeClaim:
            claimName: rabbitmq-pvc